import { ProtocolVersion } from "./data";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const WEBPACK_ENTRY = MAIN_WINDOW_WEBPACK_ENTRY;
export const PRELOAD_WEBPACK_ENTRY = MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY;

export const PROTO_TYPE_NAME_PREFIX = "type.libernet.org";

export const INITIAL_WIDTH = 800;
export const INITIAL_HEIGHT = 600;
export const CONTROL_BAR_HEIGHT = 85;

export const DEFAULT_SEARCH_ENGINE = "https://www.google.com/search?q=$QUERY$";

export const VERSION_PATTERN = /^v?([0-9]+)\.([0-9]+)\.([0-9]+)$/;

export const URL_PREFIX_PATTERN =
  /^([a-z]+):\/\/(([_a-z0-9-]+(?:\.[_a-z0-9-]+)*)(?::([0-9]+))?(?:\/.*)?)$/i;
export const DNS_NAME_PATTERN = /^[_a-z0-9-]+(?:\.[_a-z0-9-]+)*$/i;
export const DNS_PREFIX_PATTERN = /^[_a-z0-9-]+(?:\.[_a-z0-9-]+)*(?:\/|$)/i;
export const DNS_HEURISTIC_PREFIX_PATTERN =
  /^(?:localhost|(?:[_a-z0-9-]+(?:\.[_a-z0-9-]+)+))(?:\/|$)/i;

export const PROTOCOL_VERSION = new ProtocolVersion(0, 2, 0);

export const BLOCK_REWARD_TRANSACTION_DST =
  "0x2354fbdbabaab2075cbefe832071e7b85297d3dd4a9ba7074bb3487ed5e3651f";
export const SEND_COINS_TRANSACTION_DST =
  "0x42e713a7bd50ea9400810b63ffd6f04860196513b2cf9ec3608411c2c38f059b";
